fix(upgrade-packages): validate-is-root must be run before setup-output-log

diff --git a/src/upgrade-packages b/src/upgrade-packages
--- a/src/upgrade-packages
+++ b/src/upgrade-packages
@@ -48,6 +48,14 @@ stop-timer () {
   START_TIME=0
 }
 
+validate-is-root () {
+  if [[ $(/usr/bin/id -u) -ne 0 ]]
+  then
+    echo-error "Root is required"
+    exit 1
+  fi
+}
+
 setup-output-log () {
   if [[ ! -d "${OUTPUT_LOG_DIR}" ]]
   then
@@ -64,16 +72,8 @@ setup-output-log () {
   fi
 }
 
-validate-is-root() {
-  if [[ $(/usr/bin/id -u) -ne 0 ]]
-  then
-    echo-error "Root is required"
-    exit 1
-  fi
-}
-
-setup-output-log
 validate-is-root
+setup-output-log
 
 echo-information "Upgrading packages"
 echo-subsidiary "Logging verbose output to: ${OUTPUT_LOG_FILE}"
